// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1JPf19akOk1XAg7MzFBZRhZxNEAMn9yA',
    appId: '1:1064582330802:web:6ce60e8820d7281aa38cab',
    messagingSenderId: '1064582330802',
    projectId: 'gdsc-f4f71',
    authDomain: 'gdsc-f4f71.firebaseapp.com',
    storageBucket: 'gdsc-f4f71.appspot.com',
    measurementId: 'G-3XDPEC554L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMVeMZVbEjrkQP4Jy2cZ7AkW7IYf_UMf0',
    appId: '1:1064582330802:android:e8a2f859e7f1bbd6a38cab',
    messagingSenderId: '1064582330802',
    projectId: 'gdsc-f4f71',
    storageBucket: 'gdsc-f4f71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTq3CBZjxsDyHDDn5kcKl0av0R5VsDcMM',
    appId: '1:1064582330802:ios:6906612cdb5bc045a38cab',
    messagingSenderId: '1064582330802',
    projectId: 'gdsc-f4f71',
    storageBucket: 'gdsc-f4f71.appspot.com',
    iosBundleId: 'com.example.gdsc',
  );
}
